### ISSUE TITLE
Crash when no screenshot taken

### ISSUE THREAD

**Issue by hippydave** [Fusion86/ShareNX-Overlay#1]
[crash.zip](https://github.com/Fusion86/ShareNX-Overlay/files/4535401/crash.zip)
Thanks for this fork - I've found it crashes after displaying the "No screenshot taken" message, which HookedBehemoth's release doesn't do.

**Comment by Fusion86** [comment]
A bit late maybe, but it might be fixed in the v1.2.0 release.
